# Reference: https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml
run:
  timeout: 5m

issues:
  exclude-files:
    - pkg/apis/crdmetrics/register.go
    - pkg/apis/crdmetrics/v1alpha1/register.go

linters:
  disable:
    - exhaustruct
    - err113
    - gci
    - makezero
  presets:
    - bugs
    - comment
    - error
    - import
    - performance
    - test
    - unused

linters-settings:
  perfsprint:
    strconcat: false
  depguard:
    rules:
      main:
        deny:
          - pkg: "github.com/pkg/errors"
            desc: "Use 'errors' or 'fmt' instead."
          - pkg: "golang.org/x/exp/slices"
            desc: "Use 'slices' instead."
