name: continuous-integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GO_VERSION: 1.23
  RUNNER_DEBUG: 0 # Re-define repository secrets to enable this. Note that this may leak sensitive data, so remove the workflow runs after debugging.

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Vet the codebase
        run: go vet ./...
      - name: Setup dependencies
        run: make setup
      - name: Verify pkg/generated
        run: make verify-codegen
      - name: Run linter
        run: make lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v4
        with:
          path: github.com/rexagod/crdmetrics
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Create a cluster
        uses: helm/kind-action@v1
        with:
          cluster_name: kind
      - name: Run tests
        run: |
          cd github.com/rexagod/crdmetrics
          export KUBECONFIG=~/.kube/config
          kind get kubeconfig --name kind > $KUBECONFIG
          kind export kubeconfig
          make setup test
